### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by AtomicNess123** [LeNiglo/recipe_manager#1]
Apologies, I did not know of the existence of Meteor until today! How to run the program? SOme indications would be welcome. Thanks.

**Comment by LeNiglo** [comment]
Hi @Gahamelas,

Glad you are interested ! :D
This is kind of an old meteor project, might be outdated.
But if you want the quickstart, just download Meteor binary from https://www.meteor.com/install
Then you go to the folder project and type `meteor`.

You might end up with a bcrypt error, if so, just install it using `meteor npm install --save bcrypt`

That's about it :)
Feel free to ask questions.

**Comment by AtomicNess123** [comment]
Thanks so much. I have done as you say. Now... how do I run recipe manager? :))

**Comment by LeNiglo** [comment]
After executing the command `meteor` in the folder (it takes some time the first time), the application should be running on the port 3000 of your machine :)

**Comment by AtomicNess123** [comment]
Ok I see. So it's like a website where I can create recipes. Is there a search tool to it? Or basically a list with all the recipes?

**Comment by LeNiglo** [comment]
You can list whatever recipe you want, it is designed to be an open community platform where many people can share their recipe.
Once the recipe is posted, you can share it and there is a search bar also.
That's about it ^^

**Comment by AtomicNess123** [comment]
Thanks. I was more looking for a "manager", and I guess this is more of a "community".

**Comment by LeNiglo** [comment]
Yes, kindof, but you can still keep the access private and it will be your own recipe book.
